// src/pricing/types.ts
// Shared shapes for the pricing engine. Data lives in src/pricing/data/*
// (safe to ship to the browser) and src/pricing/internal/* (never shipped —
// see src/pricing/README.md for the public/internal split).

export type PricingModel = "flat" | "per_user" | "per_location" | "transaction";

export interface SoftwareTool {
  key: string;
  name: string;
  category: string;
  pricingModel: PricingModel;
  /** Estimated USD list price: flat = per business/mo; per_user = per
   * seat/mo; per_location = per location/mo; transaction = 0 (fees only). */
  estMonthly: number;
  /** Fraction of employees who typically hold a seat (per_user tools). */
  seatFraction?: number;
  transactionNote?: string;
  /** Typical one-time setup/onboarding the business already paid. */
  estImplementation: number;
  /** True only after checking the vendor's current public pricing page.
   * Everything ships as false until verified — the UI shows "estimated". */
  verified: boolean;
  sourceUrl: string;
  /** 3Stone One modules that replace this tool. Empty = we don't replace
   * it (Connect path only) — the REPLACE button is disabled with keepNote. */
  replacedByModules: string[];
  canKeepAndConnect: boolean;
  keepNote?: string;
}

export interface Industry {
  key: string;
  label: string;
  /** Software keys this kind of business typically already runs. */
  typicalStack: string[];
  /** Modules recommended regardless of what gets replaced. */
  recommendedModules: string[];
  defaultEmployees: number;
  defaultLocations: number;
}

export interface ProductModule {
  key: string;
  label: string;
  blurb: string;
  /** Included in the base platform (always on, not billed separately). */
  baseIncluded: boolean;
}

export type ToolChoice = "keep" | "replace";

export interface StackSelection {
  industryKey: string | null;
  employees: number;
  locations: number;
  /** Only tools the visitor actually uses appear here. */
  tools: Record<string, ToolChoice>;
}

export interface SpendLine {
  key: string;
  name: string;
  monthly: number;
  choice: ToolChoice;
  estimated: boolean;
  transactionNote?: string;
}

export interface CurrentSpend {
  monthly: number;
  annual: number;
  implementationPaid: number;
  keptMonthly: number;
  replacedMonthly: number;
  lines: SpendLine[];
}

export interface PriceQuote {
  modules: string[];
  monthlySubscription: number;
  implementationOneTime: number;
  /** 12 months of subscription + one-time implementation. */
  firstYearInvestment: number;
}

export type RoiOutcomeKind = "savings" | "comparable" | "premium";

export interface RoiOutcome {
  kind: RoiOutcomeKind;
  /** (kept tools + 3Stone One) − current total, per month. Negative = saving. */
  monthlyDelta: number;
  annualDelta: number;
  headline: string;
  explanation: string;
}

/** Retail rates the public page prices from. GENERATED by the internal
 * engine (npm run pricing:publish) — margins and costs never ship. */
export interface PublishedRates {
  generatedAt: string;
  basePlatformMonthly: number;
  perEmployeeMonthly: number;
  aiPerEmployeeMonthly: number;
  moduleMonthly: Record<string, number>;
  minimumMonthly: number;
  implementation: {
    base: number;
    perModule: number;
    perReplacedTool: number;
    minimum: number;
  };
}
